# ruff: noqa: I001
# Import all parsers to trigger registration with the registry.
from app.parsers import abbey_farm  # noqa: F401
from app.parsers import addington  # noqa: F401
from app.parsers import arena_uk  # noqa: F401
from app.parsers import asao  # noqa: F401
from app.parsers import ashwood  # noqa: F401
from app.parsers import ballavartyn  # noqa: F401
from app.parsers import british_dressage  # noqa: F401
from app.parsers import british_eventing  # noqa: F401
from app.parsers import british_horseball  # noqa: F401
from app.parsers import british_showjumping  # noqa: F401
from app.parsers import brook_farm  # noqa: F401
from app.parsers import bsha  # noqa: F401
from app.parsers import bsps  # noqa: F401
from app.parsers import dean_valley  # noqa: F401
from app.parsers import derby_college  # noqa: F401
from app.parsers import endurance_gb  # noqa: F401
from app.parsers import entry_master  # noqa: F401
from app.parsers import epworth  # noqa: F401
from app.parsers import equilive  # noqa: F401
from app.parsers import equipe_online  # noqa: F401
from app.parsers import equo_events  # noqa: F401
from app.parsers import generic  # noqa: F401
from app.parsers import hartpury  # noqa: F401
from app.parsers import hickstead  # noqa: F401
from app.parsers import hope_valley  # noqa: F401
from app.parsers import hpa_polo  # noqa: F401
from app.parsers import horse_events  # noqa: F401
from app.parsers import horse_monkey  # noqa: F401
from app.parsers import horsevents  # noqa: F401
from app.parsers import its_plain_sailing  # noqa: F401
from app.parsers import kelsall_hill  # noqa: F401
from app.parsers import morris  # noqa: F401
from app.parsers import my_riding_life  # noqa: F401
from app.parsers import northallerton  # noqa: F401
from app.parsers import nsea  # noqa: F401
from app.parsers import nvec  # noqa: F401
from app.parsers import outdoor_shows  # noqa: F401
from app.parsers import port_royal  # noqa: F401
from app.parsers import showground  # noqa: F401
from app.parsers import solihull  # noqa: F401
from app.parsers import sykehouse  # noqa: F401
