# ruff: noqa: I001
# Import all parsers to trigger registration with the registry.
from app.parsers import aachen  # noqa: F401
from app.parsers import abbey_farm  # noqa: F401
from app.parsers import addington  # noqa: F401
from app.parsers import al_shiraaa  # noqa: F401
from app.parsers import arc_de_triomphe  # noqa: F401
from app.parsers import azelhof  # noqa: F401
from app.parsers import arena_uk  # noqa: F401
from app.parsers import asao  # noqa: F401
from app.parsers import ashwood  # noqa: F401
from app.parsers import ballavartyn  # noqa: F401
from app.parsers import bolesworth  # noqa: F401
from app.parsers import british_dressage  # noqa: F401
from app.parsers import brussels_stephex  # noqa: F401
from app.parsers import british_eventing  # noqa: F401
from app.parsers import british_horseball  # noqa: F401
from app.parsers import british_showjumping  # noqa: F401
from app.parsers import brook_farm  # noqa: F401
from app.parsers import bsha  # noqa: F401
from app.parsers import bsps  # noqa: F401
from app.parsers import chantilly  # noqa: F401
from app.parsers import carolina_international  # noqa: F401
from app.parsers import cavaliada  # noqa: F401
from app.parsers import chatsworth  # noqa: F401
from app.parsers import chi_geneva  # noqa: F401
from app.parsers import chio_rotterdam  # noqa: F401
from app.parsers import csio_barcelona  # noqa: F401
from app.parsers import csio_roma  # noqa: F401
from app.parsers import dean_valley  # noqa: F401
from app.parsers import deauville  # noqa: F401
from app.parsers import derby_college  # noqa: F401
from app.parsers import desert_international  # noqa: F401
from app.parsers import devon_horse_show  # noqa: F401
from app.parsers import dinard  # noqa: F401
from app.parsers import dressage_at_devon  # noqa: F401
from app.parsers import dublin_horse_show  # noqa: F401
from app.parsers import dubai_sj_championship  # noqa: F401
from app.parsers import dutch_masters  # noqa: F401
from app.parsers import endurance_gb  # noqa: F401
from app.parsers import equitalyon  # noqa: F401
from app.parsers import entry_master  # noqa: F401
from app.parsers import epworth  # noqa: F401
from app.parsers import equilive  # noqa: F401
from app.parsers import equipe_online  # noqa: F401
from app.parsers import equo_events  # noqa: F401
from app.parsers import falsterbo  # noqa: F401
from app.parsers import fei_world_cup_finals  # noqa: F401
from app.parsers import fontainebleau  # noqa: F401
from app.parsers import generic  # noqa: F401
from app.parsers import global_dressage_festival  # noqa: F401
from app.parsers import great_meadow  # noqa: F401
from app.parsers import gothenburg  # noqa: F401
from app.parsers import great_yorkshire  # noqa: F401
from app.parsers import hampton_classic  # noqa: F401
from app.parsers import hartpury  # noqa: F401
from app.parsers import helsinki_horse_show  # noqa: F401
from app.parsers import hickstead  # noqa: F401
from app.parsers import hof_kasselmann  # noqa: F401
from app.parsers import hoys  # noqa: F401
from app.parsers import hope_show  # noqa: F401
from app.parsers import hope_valley  # noqa: F401
from app.parsers import hpa_polo  # noqa: F401
from app.parsers import horse_boarding_uk  # noqa: F401
from app.parsers import horse_events  # noqa: F401
from app.parsers import horse_monkey  # noqa: F401
from app.parsers import horsevents  # noqa: F401
from app.parsers import its_plain_sailing  # noqa: F401
from app.parsers import jumping_amsterdam  # noqa: F401
from app.parsers import jumping_indoor_maastricht  # noqa: F401
from app.parsers import jumping_verona  # noqa: F401
from app.parsers import kelsall_hill  # noqa: F401
from app.parsers import kentucky_three_day  # noqa: F401
from app.parsers import keysoe_international  # noqa: F401
from app.parsers import la_baule  # noqa: F401
from app.parsers import lake_placid  # noqa: F401
from app.parsers import le_siepi  # noqa: F401
from app.parsers import lgct  # noqa: F401
from app.parsers import live_oak  # noqa: F401
from app.parsers import london_international  # noqa: F401
from app.parsers import luhmuhlen  # noqa: F401
from app.parsers import madrid_horse_week  # noqa: F401
from app.parsers import maryland_5_star  # noqa: F401
from app.parsers import mondial_du_lion  # noqa: F401
from app.parsers import morris  # noqa: F401
from app.parsers import national_horse_show  # noqa: F401
from app.parsers import munich_riem  # noqa: F401
from app.parsers import my_riding_life  # noqa: F401
from app.parsers import national_equine_show  # noqa: F401
from app.parsers import northallerton  # noqa: F401
from app.parsers import nsea  # noqa: F401
from app.parsers import nvec  # noqa: F401
from app.parsers import ocala  # noqa: F401
from app.parsers import old_salem_farm  # noqa: F401
from app.parsers import oslo_horse_show  # noqa: F401
from app.parsers import osberton  # noqa: F401
from app.parsers import outdoor_shows  # noqa: F401
from app.parsers import pau  # noqa: F401
from app.parsers import peelbergen  # noqa: F401
from app.parsers import pennsylvania_national  # noqa: F401
from app.parsers import port_royal  # noqa: F401
from app.parsers import royal_cornwall  # noqa: F401
from app.parsers import royal_highland  # noqa: F401
from app.parsers import royal_welsh  # noqa: F401
from app.parsers import riesenbeck  # noqa: F401
from app.parsers import royal_windsor  # noqa: F401
from app.parsers import samorin  # noqa: F401
from app.parsers import saut_hermes  # noqa: F401
from app.parsers import scandinavia_jumping  # noqa: F401
from app.parsers import sentower_park  # noqa: F401
from app.parsers import showground  # noqa: F401
from app.parsers import solihull  # noqa: F401
from app.parsers import spruce_meadows  # noqa: F401
from app.parsers import stockholm_horse_show  # noqa: F401
from app.parsers import sunshine_tour  # noqa: F401
from app.parsers import sykehouse  # noqa: F401
from app.parsers import toscana_tour  # noqa: F401
from app.parsers import trailblazers  # noqa: F401
from app.parsers import traverse_city  # noqa: F401
from app.parsers import uae_presidents_cup  # noqa: F401
from app.parsers import upperville  # noqa: F401
from app.parsers import vilamoura  # noqa: F401
from app.parsers import washington_international  # noqa: F401
from app.parsers import wef  # noqa: F401
from app.parsers import your_horse_live  # noqa: F401
